name: Gulp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Minify and create chromium.zip
        run: |
          npm install
          gulp minify
          gulp chromiumzip
      - name: Configure git name and email
        run: |
          git config user.name "Minifier"
          git config user.email "tigerros.gh@gmail.com"
      - name: Stage changed files
        run: git add chromium.zip
      - name: Commit changed files
        run: git commit -m "Add chromium.zip"
      - name: Push code
        run: git push