name: Gulp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Minify
        run: |
          npm install
          gulp

      - name: Configure git name
        run: git config user.name "Minifier"
      - name: Configure git email
        run: git config user.email "tigerros.gh@gmail.com"
      - name: Stage changed files
        run: git add .
      - name: Commit changed files
        run: git commit -m "Add chromium.zip"
      - name: Push code to master
        run: git push origin HEAD:master